import { ServiceElement } from "../../types/types";
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

import type { AppState } from "../../app/store";

import { selectRepositoryAsync } from "../repository/repositorySlice";
import { createServiceFromState } from "./ServiceFactory";

export interface ServiceState {
  services: ServiceElement[];
  newService: ServiceElement | undefined;
  newServiceStatus: "idle" | "creating" | "editing";
  status: "empty" | "idle" | "loading" | "failed";
}

const initialState: ServiceState = {
  services: [],
  status: "empty",
  newService: undefined,
  newServiceStatus: "idle",
};

export const ServiceSlice = createSlice({
  name: "service",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    updateServices: (state, action: PayloadAction<ServiceElement[]>) => {
      state.services = action.payload;
      state.status = "idle";
    },
    initiatePopUp: (state) => {
      state.newServiceStatus = "idle";
    },
    createNewService: (state, action: PayloadAction<ServiceElement>) => {
      if (
        state.services.filter(
          (element: ServiceElement) => element.id === action.payload.id
        ).length == 0
      ) {
        state.newService = undefined;
        state.services = [...state.services, action.payload];
        state.newServiceStatus = "idle";
      }
    },
    initiateNewService: (state, action?: PayloadAction<{}>) => {
      state.newService = createServiceFromState({ ...action.payload });
      state.newServiceStatus = "creating";
      //action? state.newService = {name: action.payload, id:}
    },
    modifyService: (state, action: PayloadAction<ServiceElement>) => {
      state.newService = undefined;
      state.newServiceStatus = "idle";
      const index = state.services.findIndex(
        (element) => element.id === action.payload.id
      );
      state.services = [
        ...state.services.slice(0, index),
        action.payload,
        ...state.services.slice(index + 1),
      ];
    },
    initiateModifyService: (state, action: PayloadAction<ServiceElement>) => {
      if (
        state.newService &&
        state.newService.id === action.payload.id &&
        state.newService.type === action.payload.type
      ) {
        state.newService = undefined;
        state.newServiceStatus = "idle";
      } else {
        state.newService = createServiceFromState({ ...action.payload });
        state.newServiceStatus = "editing";
      }
    },
    cancelCreationPopUp: (state) => {
      state.newServiceStatus = "idle";
    },
    saveServicesToDraft: (state, action: PayloadAction<ServiceElement[]>) => {},
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(selectRepositoryAsync.fulfilled, (state, payload) => {
      state.services = [];
      state.status = "empty";
    });
  },
});

export const {
  initiatePopUp,
  updateServices,
  modifyService,
  createNewService,
  initiateNewService,
  initiateModifyService,
  cancelCreationPopUp,
  saveServicesToDraft,
} = ServiceSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectService = (state: AppState) => state.service;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default ServiceSlice.reducer;
